name: Deploy Review App
on:
    pull_request_target:
        types: [opened, reopened, synchronize, closed]

env:
    FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    FLY_ACCESS_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    FLY_REGION: nrt
    FLY_ORG: wsh-2026

jobs:
    review_app:
        timeout-minutes: 30
        runs-on: ubuntu-latest
        outputs:
            url: ${{ steps.deploy.outputs.url }}
        concurrency:
            group: pr-${{ github.event.number }}
            cancel-in-progress: true

        environment:
            name: deployment
            url: ${{ steps.deploy.outputs.url }}

        steps:
            - name: Get code
              uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
              with:
                  ref: ${{ github.event.pull_request.head.sha }}
                  repository: ${{ github.event.pull_request.head.repo.full_name }}
            - name: Setup flyctl
              uses: superfly/flyctl-actions/setup-flyctl@fc53c09e1bc3be6f54706524e3b82c4f462f77be # v1
            - name: Setup fly.io docker registry
              run: flyctl auth docker
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

            - name: Generate valid app name
              id: generate-app-name
              run: |
                  APP_NAME=$(grep -oP 'app = "\K[^"]+' fly.toml)
                  APP_NAME="pr-${{ github.event.number }}-${APP_NAME}"
                  echo "app_name=${APP_NAME}" >> $GITHUB_OUTPUT
                  echo "Generated app name: ${APP_NAME}"

            - name: Create Docker image file
              id: create-image-name
              run: |
                  IMAGE_NAME="registry.fly.io/${{ steps.generate-app-name.outputs.app_name }}:${{ github.event.pull_request.head.sha }}"
                  echo "image=${IMAGE_NAME}" >> $GITHUB_OUTPUT
                  echo "Generated image name: ${IMAGE_NAME}"

            - name: Create fly.io app
              run: |
                  if ! flyctl status --app ${{ steps.generate-app-name.outputs.app_name }}; then
                    flyctl apps create ${{ steps.generate-app-name.outputs.app_name }} --org ${{ env.FLY_ORG }}
                  fi

            - name: Build and push
              uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7.0.0
              with:
                  context: .
                  push: true
                  tags: ${{ steps.create-image-name.outputs.image }}

            - name: Deploy PR app to Fly.io
              id: deploy
              uses: superfly/fly-pr-review-apps@6f79ec3a7d017082ed11e7c464dae298ca75b21b # 1.2.1
              with:
                  name: ${{ steps.generate-app-name.outputs.app_name }}
                  image: ${{ steps.create-image-name.outputs.image }}
